name: quality
on:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.1
    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4.0
        skip-cache: true
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.1
    - name: Build
      run: make build
